# Program to make a simple
# login screen


from tkinter import *
import tkinter as tk
from tkinter import font as tkfont 
import os
from all_paths import username_file_path,password_file_path,email_file_path,purchase_file_path


print(username_file_path)
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title("Atarbls Installer")
window.geometry("862x519")
window.configure(bg = "#3985F6")


canvas = Canvas(
    window,
    bg = "#3985F6",
    height = 519,
    width = 862,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    393.9999999999999,
    7.105427357601002e-15,
    861.9999999999999,
    519.0,
    fill="#FCFCFC",
    outline="")

canvas.create_text(
    484.9999999999999,
    371.0,
    anchor="nw",
    text="Email :",
    fill="#000000",
    font=("Roboto Bold", 24 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda:submit(),
    relief="flat"
)
button_1.place(
    x=555.9999999999999,
    y=432.0,
    width=180.0,
    height=55.0
)

canvas.create_text(
    26.999999999999886,
    14.000000000000007,
    anchor="nw",
    text="Welcome to \nAtarbls Antivirus Installer  ",
    fill="#FCFCFC",
    font=("Roboto Bold", 24 * -1)
)

canvas.create_text(
    525.9999999999999,
    17.000000000000007,
    anchor="nw",
    text="Atarbls Installer ",
    fill="#505485",
    font=("Ruda Regular", 24 * -1)
)

canvas.create_rectangle(
    26.999999999999886,
    73.0,
    131.9999999999999,
    80.0,
    fill="#DEFF17",
    outline="")

canvas.create_rectangle(
    1.1368683772161603e-13,
    452.0,
    394.0000000000001,
    459.0,
    fill="#FB0F0F",
    outline="")

canvas.create_rectangle(
    495.9999999999999,
    52.00000000000001,
    722.9999999999999,
    57.00000000000001,
    fill="#0783F6",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    684.4999999999999,
    110.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#F1F5FF",
    highlightthickness=0
)
entry_1.place(
    x=568.9999999999999,
    y=80.0,
    width=231.0,
    height=59.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    684.4999999999999,
    199.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#F1F5FF",
    highlightthickness=0
)
entry_2.place(
    x=568.9999999999999,
    y=169.0,
    width=231.0,
    height=59.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    684.4999999999999,
    297.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#F1F5FF",
    highlightthickness=0
)
entry_3.place(
    x=568.9999999999999,
    y=267.0,
    width=231.0,
    height=59.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    684.4999999999999,
    384.5,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#F1F5FF",
    highlightthickness=0
)
entry_4.place(
    x=568.9999999999999,
    y=354.0,
    width=231.0,
    height=59.0
)

canvas.create_text(
    2.9999999999998863,
    460.0,
    anchor="nw",
    text="By Harsh Chaudhari in India",
    fill="#FCFCFC",
    font=("Acme Regular", 24 * -1)
)

canvas.create_text(
    437.9999999999999,
    186.0,
    anchor="nw",
    text="Password :",
    fill="#000000",
    font=("Roboto Bold", 24 * -1)
)

canvas.create_text(
    402.9999999999999,
    287.0,
    anchor="nw",
    text="Purchase date : ",
    fill="#000000",
    font=("Roboto Bold", 22 * -1)
)

canvas.create_text(
    435.9999999999999,
    96.0,
    anchor="nw",
    text="User Name :",
    fill="#000000",
    font=("Roboto Bold", 22 * -1)
)

canvas.create_text(
    25.999999999999886,
    96.0,
    anchor="nw",
    text="I have used Tkinter-Designer\nfor this project.",
    fill="#FCFCFC",
    font=("Acme Regular", 24 * -1)
)

canvas.create_text(
    25.999999999999886,
    188.0,
    anchor="nw",
    text="I am only one who is working\non this projects.\nSo please share this project.",
    fill="#FCFCFC",
    font=("Acme Regular", 24 * -1)
)

canvas.create_text(
    25.999999999999886,
    305.0,
    anchor="nw",
    text="This is whole new antivirus\n(This is a game).\nI think this Antivirus's UI\nis better than normal antivirus",
    fill="#FCFCFC",
    font=("Acme Regular", 23 * -1)
)





# declaring string variable
# for storing name and password


# defining a function that will
# get the name and password and
# print them on the screen
def submit():

	user_name=entry_1.get()
	password=entry_2.get()
	email=entry_4.get()
	purchase=entry_3.get()
	

	import datetime 
	from datetime import date 
	from tkinter import messagebox
             
	date_time_obj = datetime.datetime.strptime(purchase, '%d-%m-%Y').date()
	main_date = date_time_obj + datetime.timedelta(days=365)
	
	remaining_days = (main_date - date.today()).days
	messagebox.showinfo("showinfo", "Regestraion succesfully. Check your email")
	name = open(username_file_path, "w") #opens file usernames.txt and gets ready to write to it
	

	name.write(user_name) #writes contents in file to usernames.txt
	name.close() #closes file
	open1 = open(username_file_path, "r") #opens file to read it
	print (open1.read()) #prints whatever is in the text file

	#Password
	name = open(password_file_path, "w") #opens file usernames.txt and gets ready to write to it
	

	name.write(password) #writes contents in file to usernames.txt
	name.close() #closes file
	open1 = open(password_file_path, "r") #opens file to read it
	print (open1.read()) #prints whatever is in the text file

	#Email
	name = open(email_file_path, "w") #opens file usernames.txt and gets ready to write to it
	

	name.write(email) #writes contents in file to usernames.txt
	name.close() #closes file
	open1 = open(email_file_path, "r") #opens file to read it
	print (open1.read()) #prints whatever is in the text file

	#purchase
	name = open(purchase_file_path, "w") #opens file usernames.txt and gets ready to write to it
	

	name.write(purchase) #writes contents in file to usernames.txt
	name.close() #closes file
	open1 = open(purchase_file_path, "r") #opens file to read it
	print (open1.read()) #prints whatever is in the text file
	
	
	
	import smtplib, ssl
	from email.mime.text import MIMEText
	from email.mime.multipart import MIMEMultipart

	sender_email = "harshantivirus2@gmail.com"
	receiver_email = email
	password = "@Harsh2007"

	message = MIMEMultipart("alternative")
	message["Subject"] = "Ki-Lo antivirus 2.0 Subscription"
	message["From"] = sender_email
	message["To"] = receiver_email

	# Create the plain-text and HTML version of your message
	text = f"""\
	Welcome {receiver_email} to Ki-Lo Antivirus 2.5.0 
	Your subscription will be of 365 days.
	So from today or {purchase} to this {main_date}.
	And if you want visit website:
	https://github.com/harshsc2007/Kilo-Antivirus/releases"""
	html = f"""\
	<html>
	<body>
		<p>Welcome {receiver_email} to Ki-Lo Antivirus 2.5.0 ,<br>
		Your subscription will be of 365 days.<br>
		And if you want visit website:<br>
		<a href="https://github.com/harshsc2007/Kilo-Antivirus/releases">Ki-Lo the game Antivirus</a> 
		</p>
	</body>
	</html>
	"""
	# Turn these into plain/html MIMEText objects
	part1 = MIMEText(text, "plain")
	part2 = MIMEText(html, "html")

	# Add HTML/plain-text parts to MIMEMultipart message
	# The email client will try to render the last part first
	message.attach(part1)
	message.attach(part2)
	
	# Create secure connection with server and send email
	context = ssl.create_default_context()
	with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
		server.login(sender_email, password)
		server.sendmail(
			sender_email, receiver_email, message.as_string()
		)

window.resizable(False, False)	
window.mainloop()
